In [2]:
import numpy as np

In [3]:
a=np.array([2,3,4,5,5])
print(a)

[2 3 4 5 5]


In [29]:
# 1 D Array
a=np.array([2,3,4,5,5])
print(a.ndim)

1


In [31]:
# 0 D Array
a=np.array(20)
print(a.ndim)

0


In [32]:
# 2 D Array
a=np.array([[20,13,24,15,5]])
print(a.ndim)

2


In [33]:
# 3 D Array
a=np.array([[[20,12,10,4,60,7]]])
print(a.ndim)

3


In [9]:
ab=np.array([1,2,3,4,5,6,7,8])
ab
    

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
ab=np.array([1,2,3,4,5,6,7,8])
print(ab.ndim)

1


In [15]:
ab=np.array([[2,3,4,5],[6,6,7,8]])
print(ab.ndim)

2


In [12]:
ab=np.array(27)
print(ab.ndim)

0


In [18]:
ab=np.array([[2,3,4,5],[6,6,7,8]])
for x in ab:
    print(x)

[2 3 4 5]
[6 6 7 8]


In [20]:
ab=np.array([[[2,3,4,5],[6,6,7,8]]])
print(ab.ndim)

3


In [4]:
# 3 D Array
a=np.array([[[2,3,4],[2,3,4]],[[2,3,4],[2,3,4]],[[2,3,4],[2,3,4]],[[2,3,4],[2,3,4]]])
print(a,"---",a.ndim)
a.shape

[[[2 3 4]
  [2 3 4]]

 [[2 3 4]
  [2 3 4]]

 [[2 3 4]
  [2 3 4]]

 [[2 3 4]
  [2 3 4]]] --- 3


(4, 2, 3)

# Array iterating

In [21]:
ab=np.array([[2,3,4,5],[6,6,7,8]])
for x in ab:
    print(x)

[2 3 4 5]
[6 6 7 8]


In [27]:
ab=np.array([[[2,3,4,5],[6,6,7,8]]])
for x in ab:
    for y in x:
            print(y)
        


[2 3 4 5]
[6 6 7 8]


In [28]:
ab=np.array([[[2,3,4,5],[6,6,7,8]]])
for x in ab:
    for y in x:
        for y1 in y:
            print(y1)

2
3
4
5
6
6
7
8


In [34]:
ab=np.array([2,3,4,6,6,7,8])
print(len(ab))

7


# Shape(Array)

In [25]:
ab=np.array([2,3,4,6,6,7,8,4])
ab1=np.shape(ab)
ab1

(8,)

In [27]:
ab=np.array([[2,3,4,6],[6,7,8,4]])
ab1=np.shape(ab)
ab1

(2, 4)

# Array reshaping

In [40]:
ab=np.array([2,3,4,6,6,7,8,4])
a1=ab.reshape(2,4)
a1

array([[2, 3, 4, 6],
       [6, 7, 8, 4]])

In [41]:
ab=np.array([2,3,4,6,6,7,8,4,3,4])
c=ab.reshape(5,2)

In [42]:
c

array([[2, 3],
       [4, 6],
       [6, 7],
       [8, 4],
       [3, 4]])

# operations on numpy

In [43]:
ab=np.array([2,3,4,6,6,7,8,4,3,4])
ab1=np.mean(ab)

In [44]:
ab1

4.7

In [45]:
ab=np.array([2,3,4,6,6,7,8,4,3,4])
ab1=np.sum(ab)
ab1

47

In [47]:
ab=np.array([2,3,4,6,6,7,8,4,3,4])
ab1=np.max(ab)
ab1

8

In [48]:
ab=np.array([2,3,4,6,6,7,8,4,3,4])
ab1=np.min(ab)
ab1

2

In [49]:
ab=np.array([2,3,4,6,6,7,8,4,3,4])
ab1=np.std(ab)
ab1

1.8466185312619388

In [50]:
ab=np.array([2,3,4,6,6,7,8,4,3,4])
ab1=np.var(ab)
ab1

3.41

In [55]:
ab=np.array([[2,3,4,6,6,7,8,4,3,4]])
c=np.mean(ab)
c

4.7

# Array splitting

In [58]:
ab=np.array([2,3,4,5,6,7,10,23,45,56])
ab1=np.array_split(ab,5)
ab1

[array([2, 3]), array([4, 5]), array([6, 7]), array([10, 23]), array([45, 56])]

In [3]:
import numpy as np
ab=np.array([2,3,4,5,6,7,10,23,45,56])
ab1=np.array_split(ab,5)
ab1

[array([2, 3]), array([4, 5]), array([6, 7]), array([10, 23]), array([45, 56])]

In [61]:
print(ab1[5])

[7]


In [62]:
ab=np.array([2,3,4,5,6,7,10,23,45,56])
ab1=np.array_split(ab,4)

In [63]:
ab1

[array([2, 3, 4]), array([5, 6, 7]), array([10, 23]), array([45, 56])]

In [64]:
ab=np.array([2,3,4,5,6,7,10,23,45,56])
ab1=np.array_split(ab,3)

In [66]:
ab1

[array([2, 3, 4, 5]), array([ 6,  7, 10]), array([23, 45, 56])]

In [67]:
ab=np.array([2,3,4,5,6,7,10,23,45,56])
ab1=np.array_split(ab,9)

In [68]:
ab1

[array([2, 3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([10]),
 array([23]),
 array([45]),
 array([56])]

# Array searching

In [69]:
ab=np.array([2,3,4,5,6,7,10,23,45,56])
ab1=np.where(ab<=20)
ab1

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)

In [70]:
ab=np.array([2,3,4,5,6,7,10,23,45,56])
ab1=np.where(ab%2==0)
ab1

(array([0, 2, 4, 6, 9], dtype=int64),)

In [71]:
ab=np.array([2,3,4,5,6,7,10,23,45,56])
ab1=np.where(ab%2==1)
ab1

(array([1, 3, 5, 7, 8], dtype=int64),)

# ArrayJoining

In [73]:
ab1=np.array([2,3,4,5,6])
ab2=np.array([2,5,6,9,8,4])
ab3=np.concatenate((ab1,ab2))
ab3

array([2, 3, 4, 5, 6, 2, 5, 6, 9, 8, 4])

In [4]:
import numpy as np
ab1=np.array([[2,3],[4,6]])
ab2=np.array([[2,5],[9,80]])
ab3=np.concatenate((ab1,ab2),axis=1)
ab3
             

array([[ 2,  3,  2,  5],
       [ 4,  6,  9, 80]])

In [12]:
import numpy as np
ab1=np.array([[2,3],[4,6]])
ab2=np.array([[2,5],[9,80]])
ab3=np.concatenate((ab1,ab2),axis=0)
ab3

array([[ 2,  3],
       [ 4,  6],
       [ 2,  5],
       [ 9, 80]])

# Array Sorting

In [2]:
import numpy as np
ab=np.array([2,3,4,12,45,54,56,32,12])
ab1=np.sort(ab)
ab1

array([ 2,  3,  4, 12, 12, 32, 45, 54, 56])

In [3]:
ab=np.array([2,3,4,12,45,54,56,32,12])
ab1=-np.sort(-ab)
ab1


array([56, 54, 45, 32, 12, 12,  4,  3,  2])

In [4]:
ab=np.array([2,3,4,12,45,54,56,32,12])
ab1=np.flip(ab)
ab1

array([12, 32, 56, 54, 45, 12,  4,  3,  2])

In [5]:
# Array filtering

In [6]:
ab=np.array([12,23,80,12,23,34])
ab1=[True,False,True,True,False,True]
c=ab[ab1]
c

array([12, 80, 12, 34])

In [7]:
new=[]
ab=np.array([3,4,5,12,10,12,13,34])
for x in ab:
    if x<=20:
        new.append(True)
    else:
        new.append(False)
new        
        

[True, True, True, True, True, True, True, False]